name: Generate RULE-SET for Premium Edition of Clash
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "custom_direct=https://raw.githubusercontent.com/renzhaozhao/rules/main/direct.yaml" >> $GITHUB_ENV
          echo "custom_proxy=https://raw.githubusercontent.com/renzhaozhao/rules/main/proxy.yaml" >> $GITHUB_ENV
        shell: bash

      - name: Checkout the "hidden" branch
        uses: actions/checkout@v4
        with:
          ref: hidden

      - name: Generate direct.yaml file
        run: |
          echo "payload:" > direct.yaml
          curl -sSL ${custom_direct} >> direct.yaml

      - name: Generate proxy.yaml file
        run: |
          echo "payload:" > proxy.yaml
          curl -sSL ${custom_proxy} >> proxy.yaml

      - name: Move files to publish directory
        run: |
          mkdir -p publish
          cp *.yaml ./publish/

      - name: Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release
